apiVersion: v1
kind: ConfigMap
metadata:
  name: priority-classes
  namespace: hors-prod
data:
  priority.yaml: |
    ---
    apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: system-node-critical
    value: 2000001000
    globalDefault: false